site_name: Backgrounder
site_description: Run background tasks in asynchronous mode at all times.
site_url: https://backgrounder.dymmond.com

theme:
  name: "material"
  custom_dir: docs/overrides
  language: en
  palette:
    - scheme: "default"
      primary: "black"
      accent: "blue grey"
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: "material/lightbulb"
        name: "Switch to dark mode"
    - scheme: "slate"
      media: "(prefers-color-scheme: dark)"
      primary: "black"
      accent: "blue grey"
      toggle:
        icon: "material/lightbulb-outline"
        name: "Switch to light mode"
  favicon: statics/images/favicon.ico
  logo: statics/images/gray-10.png
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy

repo_name: dymmond/backgrounder
repo_url: https://github.com/dymmond/backgrounder
edit_uri: ""
plugins:
  - search
  - meta-descriptions:
      export_csv: false
      quiet: false
      enable_checks: false
      min_length: 50
      max_length: 160
      trim: false
  - markdownextradata:
      data: data
  - mkdocstrings:
      handlers:
        python:
          options:
            extensions:
              - griffe_typingdoc
            show_root_heading: true
            show_if_no_docstring: true
            preload_modules: [httpx, starlette, a2wsgi]
            inherited_members: true
            members_order: source
            separate_signature: true
            unwrap_annotated: true
            filters: ["!^_"]
            merge_init_into_class: true
            docstring_section_style: spacy
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true

nav:
  - Introduction: "index.md"
  - Tasks: "tasks.md"
  - Contributing: "contributing.md"
  - Sponsorship: "sponsorship.md"
  - Release Notes: "release-notes.md"
markdown_extensions:
  - toc:
      permalink: true
  - mdx_include:
      base_path: docs
  - admonition
  - extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ""
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

extra:
  alternate:
    - link: /
      name: English
      lang: en
